openapi: 3.0.3
info:
  title: turnej
  version: 1.0.0
paths:
  /turnej:
    get:
      tags:
        - turnej
      operationId: getTurnejFetchResult
      responses:
        200:
          description: ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TurnejFetchResult"

components:
  schemas:
    TurnejFetchResult:
      properties:
        tournaments:
          type: array
          items:
            $ref: "#/components/schemas/Tournament"
      required:
        - tournaments

    Tournament:
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        location:
          type: string
      required:
        - id
        - name
        - location
