openapi: 3.0.3
info:
  title: turnej
  version: 1.0.0
paths:
  /loadresult:
    get:
      tags:
        - turnej
      operationId: getLoadResult
      responses:
        200:
          description: ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoadResultResponse"

  /tournament:
    post:
      tags:
        - tournament
      operationId: addTournament
      requestBody:
        description: ""
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Tournament"
      responses:
        201:
          description: created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Tournament"

components:
  schemas:
    LoadResultResponse:
      properties:
        tournaments:
          type: array
          items:
            $ref: "#/components/schemas/Tournament"
        players:
          type: array
          items:
            $ref: "#/components/schemas/Player"
      required:
        - players

    Tournament:
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        location:
          type: string
      required:
        - id
        - name
        - location

    Player:
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
      required:
        - id
        - name


